apiVersion: v1
kind: Service
metadata: 
  name: node-web-app
  labels:
    app: node-web-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32321
  selector:
    app: node-web-app
    tier: frontend