apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node-web-app
  labels:
    app: node-web-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web-app
      tier: frontend
  template:
    metadata:
      labels:
        app: node-web-app
        tier: frontend
    spec:
      containers:
      - name: node-web-app
        image: localhost:5000/node-web-app:v1       
        ports:
        - containerPort: 8080
